name: 'mdAL'
description: 'Generate AL code from mdAL model files'
author: 'joneug'
inputs:
    model-file:
        description: 'The mdAL model file'
        required: true
runs:
  using: 'node12'
  main: 'index.js'
