name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          model-file: '-v'
